compas-dev/compas_view2

scripts/v120_polyline.py
src/compas_view2/objects/__init__.py
src/compas_view2/objects/lineobject.py
src/compas_view2/objects/polylineobject.py

Added a polyline object similar to old viewer, @Licini @tomvanmele @brgcode code can be tested in `scripts/v120_polyline.py`

add polyline object

---

scripts/v120_arrows.py
src/compas_view2/objects/__init__.py
src/compas_view2/objects/arrowobject.py
src/compas_view2/objects/shapeobject.py
src/compas_view2/shapes/__init__.py
src/compas_view2/shapes/arrow.py

Adding the `Arrow` under `shapes` folder (which can be migrated to compas later) and corresponding  `ArrowObject`.
testing script: `scripts/v120_arrows.py`

Add Arrow and ArrowObject

---

src/compas_view2/app/selector.py
src/compas_view2/objects/axisobject.py
src/compas_view2/objects/gridobject.py
src/compas_view2/objects/meshobject.py
src/compas_view2/objects/networkobject.py
src/compas_view2/objects/polylineobject.py
src/compas_view2/views/view.py
src/compas_view2/views/view120.py

The projection matrix needs to be updated when zooming with orthogonal camera. #24

fix ortho camera zoom

---

src/compas_view2/app/selector.py
src/compas_view2/views/view.py
src/compas_view2/views/view120.py

Hope it makes more sense now : )

Rename selector attributes

---

src/compas_view2/app/app.py

expose show_grid as app parameter

---

src/compas_view2/objects/meshobject.py
src/compas_view2/objects/shapeobject.py

add more custom options for meshobject

---

src/compas_view2/objects/__init__.py

register block as mesh object

---

src/compas_view2/app/config.json
src/compas_view2/app/controller.py
src/compas_view2/app/selector.py
src/compas_view2/forms/__init__.py
src/compas_view2/forms/editform.py
src/compas_view2/forms/form.py
src/compas_view2/forms/pointedit.py
src/compas_view2/objects/pointobject.py

Adding a non-blocking edit form class that can update selected object in real-time.
We need to finish the dynamic updating in #21 first to have this fully working

prototype edit forms

---

src/compas_view2/app/app.py
src/compas_view2/app/config.json
src/compas_view2/app/controller.py
src/compas_view2/objects/bufferobject.py
src/compas_view2/views/view120.py

add wireframe mode

---

scripts/v120_transform.py
src/compas_view2/app/selector.py
src/compas_view2/objects/bufferobject.py
src/compas_view2/objects/object.py
src/compas_view2/shaders/120/mesh.vert

Adding transform to base object:
- added translation, rotation (Euler XYZ), scale vector
- matrix dynamically updated from above vectors
Example:
`scripts/v120_transform.py`

add transformation matrix

---

src/compas_view2/app/app.py
src/compas_view2/app/config.json
src/compas_view2/app/controller.py
src/compas_view2/objects/bufferobject.py
src/compas_view2/shaders/120/mesh.frag
src/compas_view2/shaders/120/mesh.vert
src/compas_view2/views/view120.py

This was not requested, but I think it's cool to have

Adding lighted mode

---

scripts/v120_points.py
src/compas_view2/objects/__init__.py
src/compas_view2/objects/pointcloudobject.py

add point cloud object

---

src/compas_view2/objects/bufferobject.py
src/compas_view2/objects/gridobject.py
src/compas_view2/shaders/shader.py

#53  The background option is now added to bufferobject, that can actually be used by any classes now.

Grid to background

---

scripts/v120_arrows.py
scripts/v120_dynamic_mesh.py
scripts/v120_mesh_display.py
scripts/v120_scripted.py
src/compas_view2/objects/meshobject.py

I think it might make more sense to still use `show_vertices` and `show_edges` instead of `show_points` `show_lines` for `Mesh` based classes. Let me known what you guys think.

use vertices/edges instead of points/lines for mesh

---

.github/workflows/build.yml
.github/workflows/docs.yml
tests/test_dummy.py

use custom actions

---

scripts/v120_record.py
src/compas_view2/app/app.py
src/compas_view2/app/timer.py
src/compas_view2/views/view120.py

Added basic recording functionality with PIL, you can test with `v120_record.py`, the file does come out a bit big still. Maybe we can get the basic up and running first and then work on optimizing?

add basic recording

---

requirements.txt
src/compas_view2/app/__init__.py
src/compas_view2/app/app.py
src/compas_view2/app/config.json
src/compas_view2/objects/bufferobject.py
src/compas_view2/objects/object.py
src/compas_view2/views/view120.py

Random tweaks

---

scripts/v120_nurbs.py
src/compas_view2/forms/editform.py
src/compas_view2/objects/__init__.py
src/compas_view2/objects/bufferobject.py
src/compas_view2/objects/meshobject.py
src/compas_view2/objects/nurbssurfaceobject.py

```
from compas.geometry import Point
from compas_occ.geometry import NurbsSurface
from compas_view2.app import App
points = [
[Point(0, 0, 0), Point(1, 0, 0), Point(2, 0, 0), Point(3, 0, 0)],
[Point(0, 1, 0), Point(1, 1, 2), Point(2, 1, 2), Point(3, 1, 0)],
[Point(0, 2, 0), Point(1, 2, 2), Point(2, 2, 2), Point(3, 2, 0)],
[Point(0, 3, 0), Point(1, 3, 0), Point(2, 3, 0), Point(3, 3, 0)],
]
surface = NurbsSurface.from_points(points=points)
view = App()
view.add(surface, show_points=True, show_lines=True, pointcolor=(1, 0, 0), linecolor=(0, 0, 1))
view.run()
```

add nurbs surface object support

---

src/compas_view2/app/config.json

minor spelling error

---

scripts/v120_nurbs.py

correct the occ example import namespace

fix occ example import error

---

scripts/v120_flow.py
src/compas_view2/app/app.py
src/compas_view2/flow/__init__.py
src/compas_view2/flow/flow.py
src/compas_view2/flow/node.py
src/compas_view2/flow/values.py
src/compas_view2/flow/widgets.py

Added option to enable/disable auto update of each nodes and execute update manually from right click menu.
Still working on:
- Global execute all command
- Visual hint to indicate is node auto update is enabled
- Perhaps add an `execute` button directly on node widget

manual execution and predefined nodes

---

scripts/v120_flow.py
src/compas_view2/app/config.json
src/compas_view2/app/controller.py
src/compas_view2/flow/__init__.py
src/compas_view2/flow/flow.py
src/compas_view2/flow/node.py
src/compas_view2/flow/values.py
src/compas_view2/flow/widgets.py

Added various updates:
- Global `Run All` , `Enable Auto Update`, `Disable Auto Update` function
- More comprehensive Data inputs widgets (String, Choice)
- Nodes automatically turn red after code execution fail

more features to Ryven flow integration

---

scripts/v120_csg_flow.py
src/compas_view2/app/app.py
src/compas_view2/app/controller.py
src/compas_view2/flow/flow.py
src/compas_view2/flow/node.py
src/compas_view2/flow/widgets.py

```python
from compas.geometry import Point, Vector, Plane
from compas.geometry import Box, Cylinder
from compas.datastructures import Mesh
from compas_occ.brep import BRep
from compas_view2.app import App
from compas_view2.flow import Node, FloatNode
P = Point(0, 0, 0)
X = Vector(1, 0, 0)
Y = Vector(0, 1, 0)
Z = Vector(0, 0, 1)
YZ = Plane(P, X)
ZX = Plane(P, Y)
XY = Plane(P, Z)
viewer = App(viewmode='lighted', width=1500, height=1000, show_flow=True, flow_auto_update=True)
@Node(viewer, hide_output=True)
def create_box(size: float) -> Box:
return Box.from_width_height_depth(size, size, size)
@Node(viewer, hide_output=True)
def create_cylinder_x(radius: float, height: float) -> Box:
YZ = Plane(P, X)
return Cylinder((YZ, radius), height)
@Node(viewer, hide_output=True)
def …
```

CSG example

---

CHANGELOG.md
requirements-dev.txt
src/compas_view2/app/app.py

Optional flow

---

CHANGELOG.md
scripts/v120_tree_interactive.py
src/compas_view2/app/app.py
src/compas_view2/forms/treeform.py

`scripts/v120_tree_interactive.py`

make tree form more versatile

---

CHANGELOG.md
scripts/v120_tabs_tree_form.py
src/compas_view2/app/app.py
src/compas_view2/forms/tabsform.py

Example at: `scripts/v120_tabs_tree_form.py` 
- The input is list of name, data pairs for each tabs
- the data field of tab item corresponds to the data arguments for tree form.  
- rest of arguments are the same with tree form and passed onto individua tree forms.

add tabs form

---

CHANGELOG.md
scripts/v120_settings.py
scripts/v120_tree_editable.py
src/compas_view2/forms/treeform.py
src/compas_view2/values/__init__.py
src/compas_view2/values/boolvalue.py
src/compas_view2/values/dictvalue.py
src/compas_view2/values/floatvalue.py
src/compas_view2/values/intvalue.py
src/compas_view2/values/listvalue.py
src/compas_view2/values/settings.py
src/compas_view2/values/strvalue.py
src/compas_view2/values/value.py

Started to add value classes that strong types everything.
For example `IntValue` class would also check for data type, min and max etc.
@brgcode Could you take look at this example `scripts/v120_tree_editable.py` And let me know if this is on the right direction?
```python
data = [
{"column1": "a", "column2": IntValue(1), "on_item_edited": on_item_edited, "some_binded_obj": {}},
{"column1": "b", "column2": IntValue(2, min=0, max=10), "on_item_edited": on_item_edited},
{"column1": "c", "column2": IntValue(3, options=[0, 1, 2, 3]), "on_item_edited": on_item_edited},
]
```

add value classes

---

CHANGELOG.md
src/compas_view2/views/view.py

Multi cursor visual effect

---

CHANGELOG.md
scripts/v120_fonts.py
src/compas_view2/objects/textobject.py
src/compas_view2/shapes/text.py

Text font option

---

CHANGELOG.md
src/compas_view2/objects/bufferobject.py
src/compas_view2/scene/camera.py
src/compas_view2/shapes/text.py
src/compas_view2/views/view.py

Zoom selected enhancement

---

CHANGELOG.md
src/compas_view2/app/app.py
src/compas_view2/app/config_default.json

Full screen option

---

CHANGELOG.md
src/compas_view2/app/app.py
src/compas_view2/app/config_default.json
src/compas_view2/app/controller.py
src/compas_view2/app/selector.py
src/compas_view2/views/view.py

Move mouse and key actions to controller

---

CHANGELOG.md
docs/examples/control/example_custom_keys.py
docs/examples/control/example_custom_keys.rst
src/compas_view2/app/controller.py

This PR will alow `Custom mouse and key actions through config`. Users can define their keys in the config file.
-   Add example `example_custom_keys.py` in the examples/control.
-   Action class which controls all the key actions.

Custom mouse and key actions through config
